name: jms-docker-fe
services:

  jms-fe:
    image: jms-fe
    container_name: jms-fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - /etc/letsencrypt/live/jms.katrantech.com/fullchain.pem:/etc/nginx/certs/domain.crt
      - /etc/letsencrypt/live/jms.katrantech.com/privkey.pem:/etc/nginx/certs/domain.key
    ports:
      - '3000:80'
      - '443:443'
    networks:
      - jms-network

networks:
  jms-network:
    external: true