version: '3.7'
name: jms-docker
services:

  jms-fe:
    image: jms-fe
    container_name: jms-fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      # - /app/node_modules
    ports:
      - '3000:80'
    networks:
      - jms-network

networks:
  jms-network:
    name: jms-network
    driver: bridge