version: '3.7'

services:

  jms-fe-app:
    container_name: jms-fe
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      # - /app/node_modules
    ports:
      - '3000:80'