export const ORGANIZATION_READ = "ORGANIZATION_READ";
export const ORGANIZATION_DELETE = "ORGANIZATION_DELETE";

export const ORGANIZATION_USER_ADD = "ORGANIZATION_USER_ADD";
export const ORGANIZATION_USER_DELETE = "ORGANIZATION_USER_DELETE";
export const ORGANIZATION_USER_READ = "ORGANIZATION_USER_READ";
export const ORGANIZATION_USER_ROLES_READ = "ORGANIZATION_USER_ROLES_READ";

export const ORGANIZATION_RESOURCE_ADD = "ORGANIZATION_RESOURCE_ADD";
export const ORGANIZATION_RESOURCE_DELETE = "ORGANIZATION_RESOURCE_DELETE";
export const ORGANIZATION_RESOURCE_READ = "ORGANIZATION_RESOURCE_READ";
export const ORGANIZATION_RESOURCE_TRANSFER = "ORGANIZATION_RESOURCE_TRANSFER";

export const ORGANIZATION_PRODUCT_CREATE = "ORGANIZATION_PRODUCT_CREATE";
export const ORGANIZATION_PRODUCT_UPDATE = "ORGANIZATION_PRODUCT_UPDATE";
export const ORGANIZATION_PRODUCT_DELETE = "ORGANIZATION_PRODUCT_DELETE";
export const ORGANIZATION_PRODUCT_TRANSFER = "ORGANIZATION_PRODUCT_TRANSFER";
export const ORGANIZATION_PRODUCT_READ = "ORGANIZATION_PRODUCT_READ";

export const ORGANIZATION_SALE_CREATE = "ORGANIZATION_SALE_CREATE";
export const ORGANIZATION_SALE_PRODUCT_RETURN =
  "ORGANIZATION_SALE_PRODUCT_RETURN";
export const ORGANIZATION_SALE_READ = "ORGANIZATION_SALE_READ";
export const ORGANIZATION_SALE_RESOURCE_RETURN =
  "ORGANIZATION_SALE_RESOURCE_RETURN";

export const ORGANIZATION_ROLE_ASSIGN = "ORGANIZATION_ROLE_ASSIGN";
export const ORGANIZATION_ROLE_READ = "ORGANIZATION_ROLE_READ";
export const ORGANIZATION_ROLE_UPDATE = "ORGANIZATION_ROLE_UPDATE";

export const ORGANIZATION_EVENT_READ = "ORGANIZATION_EVENT_READ";

export const SYSTEM_USER_READ = "SYSTEM_USER_READ";
export const SYSTEM_USER_CREATE = "SYSTEM_USER_CREATE";
export const SYSTEM_USER_UPDATE = "SYSTEM_USER_UPDATE";
export const SYSTEM_USER_DELETE = "SYSTEM_USER_DELETE";

export const SYSTEM_ROLE_CREATE = "SYSTEM_ROLE_CREATE";
export const SYSTEM_ROLE_DELETE = "SYSTEM_ROLE_DELETE";
export const SYSTEM_ROLE_READ = "SYSTEM_ROLE_READ";

export const SYSTEM_RESOURCE_READ = "SYSTEM_RESOURCE_READ";
export const SYSTEM_RESOURCE_CREATE = "SYSTEM_RESOURCE_CREATE";
export const SYSTEM_RESOURCE_UPDATE = "SYSTEM_RESOURCE_UPDATE";
export const SYSTEM_RESOURCE_DELETE = "SYSTEM_RESOURCE_DELETE";
export const SYSTEM_RESOURCE_IMPORT = "SYSTEM_RESOURCE_IMPORT";

export const SYSTEM_EVENT_READ = "SYSTEM_EVENT_READ";

export const SYSTEM_ORGANIZATION_CREATE = "SYSTEM_ORGANIZATION_CREATE";
