name: Build and test

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

permissions:
  id-token: write
  contents: write

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
    - name: Install with npm
      run: npm install
    - name: Build with npm
      run: npm run build -- --mode prod
    - name: Copy built app to target folder
      run: |
        cp -r dist docker_tests/app
    - name: Start docker containers with BE and FE
      run:
        docker compose -f docker_tests/docker-compose.yml up -d
    # tests
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
