import {
  getRandomNumberAsString,
  getRandomString,
} from "./getRandomNumberOrString";

export const pearlFormFields = [
  {
    label: "Type",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Quality",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Shape",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Shape Specification",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: false,
  },
  {
    label: "Color",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Color Hue",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: false,
  },
  {
    label: "Size",
    value: getRandomNumberAsString(),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Price per quantity",
    value: getRandomNumberAsString(),
    required: true,
  },
  { label: "Note", value: getRandomString(10), required: false },
];

export const diamondFormFields = [
  {
    label: "Shape",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  { label: "Length", value: getRandomNumberAsString(), required: true },
  { label: "Width", value: getRandomNumberAsString(), required: true },
  { label: "Depth", value: getRandomNumberAsString(), required: true },
  {
    label: "Carat",
    value: getRandomNumberAsString(),
    sku: getRandomNumberAsString(),
    required: true,
  },
  {
    label: "Color",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  { label: "Color Hue", value: getRandomString(4), required: false },
  {
    label: "Clarity",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Cut",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Polish",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Symmetry",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Fluorescence",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  { label: "Price Per Unit", value: getRandomNumberAsString(), required: true },
  {
    label: "Certificate",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: false,
  },
  { label: "Note", value: getRandomString(10), required: false },
];

export const diamondMeleeFormFields = [
  {
    label: "Shape",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Size",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  { label: "Carat", value: getRandomNumberAsString(), required: true },
  {
    label: "Color",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Clarity",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Cut",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  { label: "Price Per Unit", value: getRandomNumberAsString(), required: true },
  { label: "Note", value: getRandomString(10), required: false },
];

export const coloredStoneFormFields = [
  {
    label: "Shape",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  { label: "Length", value: getRandomNumberAsString(), required: true },
  { label: "Width", value: getRandomNumberAsString(), required: true },
  { label: "Depth", value: getRandomNumberAsString(), required: true },
  {
    label: "Carat",
    value: getRandomNumberAsString(),
    sku: getRandomNumberAsString(),
    required: true,
  },
  {
    label: "Color",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  { label: "Color Hue", value: getRandomString(4), required: false },
  {
    label: "Clarity",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Cut",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  { label: "Treatment", value: getRandomString(4), required: true },
  { label: "Price Per Unit", value: getRandomNumberAsString(), required: true },
  {
    label: "Certificate",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: false,
  },
  { label: "Note", value: getRandomString(10), required: false },
];

export const coloredStoneMeleeFormFields = [
  {
    label: "Shape",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Size",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  { label: "Carat", value: getRandomNumberAsString(), required: true },
  {
    label: "Color",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  { label: "Color Hue", value: getRandomString(4), required: false },
  {
    label: "Clarity",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Cut",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  { label: "Treatment", value: getRandomString(4), required: true },
  { label: "Price Per Unit", value: getRandomNumberAsString(), required: true },
  { label: "Note", value: getRandomString(10), required: false },
];

export const semiPreciousStoneFormFields = [
  {
    label: "Type",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Quality",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Shape",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Shape Specification",
    value: getRandomNumberAsString(),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Color",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Color Hue",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: false,
  },
  {
    label: "Size",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Price per quantity",
    value: getRandomNumberAsString(),
    required: true,
  },
  { label: "Note", value: getRandomString(15), required: false },
];

export const metalFormFields = [
  {
    label: "Color",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: true,
  },
  {
    label: "Purity",
    value: getRandomNumberAsString(),
    sku: getRandomNumberAsString(),
    required: true,
  },
  {
    label: "Price per quantity",
    value: getRandomNumberAsString(),
    required: true,
  },
  { label: "Note", value: getRandomString(10), required: false },
];

export const elementFormFields = [
  {
    label: "Description",
    exact: true,
    value: getRandomString(10),
    required: true,
  },
  {
    label: "Quantity Type",
    value: getRandomString(4),
    sku: getRandomString(2),
    required: false,
  },
  {
    label: "Price per quantity",
    value: getRandomNumberAsString(),
    required: true,
  },
  { label: "Note", value: getRandomString(15), required: false },
];

export const resourceTypesData = [
  {
    type: "Pearl",
    pageTitle: "Add Pearl",
    selectFieldLabel: "Quantity Type",
    selectFieldValue: "Strand",
    fields: pearlFormFields,
    initialSku: "P.S.",
    button: "Pearl",
    childButton: "Strand",
    filter: "quantityType",
    filterValue: "Strand",
    filterButtonValues: ["STRAND", "PIECE"],
  },
  {
    type: "Diamond",
    pageTitle: "Add Diamond",
    selectFieldLabel: "Type",
    selectFieldValue: "Natural",
    fields: diamondFormFields,
    initialSku: "D.Nat.",
    button: "Diamond",
    childButton: "Natural",
    filter: "type",
    filterValue: "Natural",
    filterButtonValues: ["NATURAL", "LAB GROWN"],
  },
  {
    type: "DiamondMelee",
    pageTitle: "Add Diamond Melee",
    selectFieldLabel: "Type",
    selectFieldValue: "Natural",
    fields: diamondMeleeFormFields,
    initialSku: "D.M.Nat.",
    button: "Diamond Melee",
    childButton: "Natural Melee",
    filter: "type",
    filterValue: "Natural",
    filterButtonValues: ["NATURAL", "LAB GROWN"],
  },
  {
    type: "ColoredStone",
    pageTitle: "Add Colored Stone",
    selectFieldLabel: "Type",
    selectFieldValue: "Sapphire",
    fields: coloredStoneFormFields,
    initialSku: "CS.Sp.",
    button: "Colored Stone",
    childButton: "Piece",
    filter: "quantityType",
    filterValue: "Piece",
    filterButtonValues: ["PIECE"],
  },
  {
    type: "ColoredStoneMelee",
    pageTitle: "Add Colored Stone Melee",
    selectFieldLabel: "Type",
    selectFieldValue: "Sapphire",
    fields: coloredStoneMeleeFormFields,
    initialSku: "CS.M.Sp.",
    button: "Colored Stone Melee",
    childButton: "Piece",
    filter: "quantityType",
    filterValue: "Piece",
    filterButtonValues: ["PIECE"],
  },
  {
    type: "SemiPreciousStone",
    pageTitle: "Add Semi Precious Stone",
    selectFieldLabel: "Quantity Type",
    selectFieldValue: "Strand",
    fields: semiPreciousStoneFormFields,
    initialSku: "SP.S.",
    button: "Semi Precious Stone",
    childButton: "Strand",
    filter: "quantityType",
    filterValue: "Strand",
    filterButtonValues: ["STRAND", "PIECE"],
  },
  {
    type: "Metal",
    pageTitle: "Add Metal",
    selectFieldLabel: "Type",
    selectFieldValue: "Gold",
    fields: metalFormFields,
    initialSku: "M.G.",
    button: "Metal",
    childButton: "Gold",
    filter: "type",
    filterValue: "Gold",
    filterButtonValues: ["GOLD", "SILVER", "PLATINUM", "OTHER"],
  },
  {
    type: "Element",
    pageTitle: "Add Element",
    fields: elementFormFields,
    initialSku: "E.",
    button: "Element",
    childButton: "All Elements",
  },
];
